# Generated by Django 5.0.6 on 2026-07-02 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=200)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('wanted', 'Wanted'), ('captured', 'Captured')], default='wanted', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('danger_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
